addons:
  apt:
    packages:
    - libxml-xpath-perl
env:
  - SERVICESVER=2.4.6
  - SERVICESVER=2.4.7  
  - SERVICESVER=2.4.8
  - SERVICESVER=2.4.9

sudo: required
language: java
jdk: openjdk8
before_install:
- "./src/main/scripts/ci/before-install.sh"
- "./src/main/scripts/cd/before-deploy.sh"
after_success: "./src/main/scripts/ci/after-success.sh"
deploy:
- provider: script
  script:
  - "./src/main/scripts/cd/deploy.sh"
  on:
    branch: develop
- provider: script
  script:
  - "./src/main/scripts/cd/release.sh"
  on:
    branch: master
